name: Deploy Website

on:
  push:
    paths:
      - 'Website/**'
  workflow_dispatch:

jobs:
  build_and_deploy_stapp:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build And Deploy Stapp
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.STAPP_WEBSITE_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Website" # App source code path
          output_location: "public"
          app_build_command: 'npm run build'
          ###### End of Repository/Build Configurations ######

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_MANAGED_IDENTITY_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_MANAGED_IDENTITY_TENANTID }}
          subscription-id: ${{ secrets.AZURE_MANAGED_IDENTITY_SUBSCRIPTIONID }}
  
      - name: Upload views to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az storage blob upload-batch --account-name stehrenmeterviews --overwrite true --auth-mode login -d 'views' -s Website/src/views
              az storage blob upload --account-name stehrenmeterviews --overwrite true --auth-mode login --container-name 'views' --file Website/public/styles.css --name styles.css
  
    # Azure logout
      - name: logout
        run: |
              az logout
        if: always() 
        
